/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catstreet;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Timer;
import java.util.TimerTask;


/**
 *
 * @author wildf
 */
public class TimerProba2 extends javax.swing.JFrame implements ActionListener{
    int secondpassed=0;
      Timer timer;
    
 TimerTask task=new TimerTask() {
         @Override
         public void run() {
             secondpassed++;
             System.out.println("second passed:"+secondpassed);
              
          do{
               int leptek = 8;
        for (int i = 0; i < 5; i++) {
             

            Point helybalmacska = c1.getLocation();
            Point helyjobmacska = c2.getLocation();
            helybalmacska.x += leptek;
            helyjobmacska.x -= leptek;
            c1.setLocation(helybalmacska);
            c2.setLocation(helyjobmacska);
            
        }
              
          }while(secondpassed==5);
          
         }
     };
 
 public void start(){
  
          timer = new Timer();
          timer.scheduleAtFixedRate(task, 0, 250);
   timer.purge();
    
    
 }
    /**
     * Creates new form TimerProba2
     */
    public TimerProba2() {
        initComponents();
        jButton1.addActionListener(this);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        c1.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\CatStreet\\kepek\\attackingcat.jpg")); // NOI18N
        c1.setText("jLabel1");

        c2.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\CatStreet\\kepek\\attackingcat2.jpg")); // NOI18N
        c2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerProba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerProba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerProba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerProba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerProba2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
//        if(e.getSource()==jButton1){
//           jButton1.setText("támadás!");
//           start();  
//        }else if(jButton1.getText().equals("támadás!")){
//            jButton1.setText("jButton");
////           Timer timer2=new Timer();
////           timer2.scheduleAtFixedRate(task, 0, 300);
           start();
//            timer.cancel();
//            task.cancel();
//           timer.purge();
//           timer.purge();
//           repaint();
        }
      
//      https://stackoverflow.com/questions/21682031/i-cant-start-a-timer-2-times
        
       
//        if(e.getSource()==jButton1){
//             int leptek = 8;
////        for (int i = 0; i < 10; i++) {
//             
////            timer.setDelay(500);
//           
////            System.out.println("timer" + i);
//            Point helybalmacska = c1.getLocation();
//            Point helyjobmacska = c2.getLocation();
//
//            helybalmacska.x += leptek;
//            helyjobmacska.x -= leptek;
//            
//            
//            
//            c1.setLocation(helybalmacska);
//            c2.setLocation(helyjobmacska);
            
//        }
//    }
}
  


